# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Chạy khi có code đẩy lên nhánh main
  push:
    branches:
      - main # Hoặc 'master' nếu nhánh chính của bạn tên là master

  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Cấp quyền cho GITHUB_TOKEN để deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Chỉ cho phép một lần deploy chạy tại một thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: false

# Cấu hình môi trường mặc định
defaults:
  run:
    shell: bash

jobs:
  # Job Build: Xây dựng web từ Markdown sang HTML
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.128.0 # Phiên bản Hugo (có thể để mặc định)
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Tải cả Theme PaperMod về

      - name: Build with Hugo
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Job Deploy: Đẩy lên GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
